### PR TITLE
googletest download and build using DownloadProject

### PR DESCRIPTION
**Pull request by khalid-m**
I have added added DownloadProject which builds downloads and builds the googletest. Please reveiw it.

### CODE REVIEW

**Comment by mehdial** [comment]
When I pull from the repo, the ext/DownloadProject/ directory is empty. Therefore the project is not going to be built.

**Comment by mehdial** [comment]
When I pull from the repo, the ext/DownloadProject/ directory is empty. Therefore the project is not going to be built.

**Comment by khalid-m** [comment]
It's very strange that the files in the ext/DownloadProject were not added. Here I found the solution at https://stackoverflow.com/questions/24472596/git-fatal-pathspec-is-in-submodule
git rm --cached ext -r
  git add ext

**Comment by khalid-m** [comment]
It's very strange that the files in the ext/DownloadProject were not added. Here I found the solution at https://stackoverflow.com/questions/24472596/git-fatal-pathspec-is-in-submodule
git rm --cached ext -r
git add ext

**Comment by mehdial** [comment]
Perfect, it works now. I merge it then.

**Pull request merged**
